plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Oscar Olivetti
description: Sitio web personal
lang: en
locale: en_GB
url: ""
baseurl: "failosophy/"

# RSS feeds
feed:
  posts_limit: 20
