plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: El equipo
description: Sitio web del seminario de Modelos y  Representaciones
lang: en
locale: en_GB
url: ""
baseurl: "modeyrep/"

# RSS feeds
feed:
  posts_limit: 20
